### ISSUE TITLE
Wrong config tab opens for grammar checking

### ISSUE THREAD

**Issue by GegznaV** [nevrome/wellspell.addin#25]
Even if the grammar checking tool is used, in configuration gadget the tab with the spellchecking options is opened. It is a bit confusing. It would be better if a correct tab would open. It is even more confusing when "hunspell" is not installed and a warning message appears instead of option to choose the language for grammar checking.

**Comment by nevrome** [comment]
I fixed that, but I think now the two setting addins for spell- and grammar check should be completely independent. That's something for the future.

**Comment by GegznaV** [comment]
Now the add-in opens the correct tab.

>  I think now the two setting addins for spell- and grammar check should be completely independent.

I totally agree with his idea. It would require less time to open configuration if only one tool is required.
