### ISSUE TITLE
Error : Marker message is unspecified or invalid

### ISSUE THREAD

**Issue by GegznaV** [nevrome/wellspell.addin#26]
I ran the spellchecked with `en_US` distionary on the thext:
```r
context <- rstudioapi::getSourceEditorContext()
```

And got the following error message:

> Error : Marker message is unspecified or invalid: rstudioapi<U+2007><U+2007><U+2007><U+2007><U+2007><U+2007><U+2007><U+2007><U+2007><U+2007> | studious

It looks like an encoding issue. Is it possible to get a more informative error message?

**Comment by nevrome** [comment]
Please test if c84dd3b fixes this, @GegznaV

**Comment by GegznaV** [comment]
Works well now
