### ISSUE TITLE
Progress bar stops at less than 100% with no error message

### ISSUE THREAD

**Issue by GegznaV** [nevrome/wellspell.addin#27]
The progress bar of spellchecker does not always come to 100%. Here is a print screen:

![image](https://user-images.githubusercontent.com/12725868/73600895-09188400-4560-11ea-8f9c-1d72c1b2654a.png)

E.g., when I run the spellchecker tool (`en_US` dictionary) on the text
```r
  if (as.character(unlist(context$selection)["text"]) == "") {
    stop("No text selected.", call. = FALSE)
  }
```
I get only 33%:

![image](https://user-images.githubusercontent.com/12725868/73600953-200ba600-4561-11ea-938c-0f5d868cf38b.png)

Is this behavior expected or is there a hidden issue?

**Comment by nevrome** [comment]
Please check if 93f5822 solves this for you, @GegznaV

**Comment by GegznaV** [comment]
Nice solution 👍
