### ISSUE TITLE
All three addins fail to work on Windows

### ISSUE THREAD

**Issue by GegznaV** [nevrome/wellspell.addin#7]
![image](https://user-images.githubusercontent.com/12725868/62668075-1bd84480-b993-11e9-9968-afcdf6bbcbcc.png)

The grammar and spelling checking addins fail with error:

![image](https://user-images.githubusercontent.com/12725868/62668019-e0d61100-b992-11e9-9749-99ca8f1e03a1.png)

And the configuration addin also fails.
The error is simmilar to one reported in nevrome/LanguageToolR#2:
```r
wellspell.addin:::set_config()
#> Error: Unable to access jarfile ~/LanguageTool-4.4/languagetool-commandline.jar
#>Error in languagetool(list_languages = TRUE) : 
#>  The provided executable is not available or does not work correctly. You can install #>LanguageTool with the quick_setup() function.
```
Session info is the same as in nevrome/LanguageToolR#2.

**Can these errors be fixed?**

**Comment by nevrome** [comment]
The Language Tool grammer + etc. check can't work on windows system as long as the `LanguageToolR` package does not work there -- as described in nevrome/LanguageToolR#2.

But the hunspell spelling check should work. Unfortunately the `set_config()` function assumes that both the `hunspell` as well as the `LanguageToolR` package are available and working (e.g. https://github.com/nevrome/wellspell.addin/blob/0654c371f0b4891510cf0f681dd2451166791700/R/wellspell_config.R#L30). I have to untangle this to make sure that hunspell and Language Tool work independently.

**Comment by nevrome** [comment]
@GegznaV I separated the configuration of LanguageTool and hunspell in the config addin. That should make it possible to use the check with hunspell also when LanguageTool is not installed/does not work and vice versa. Would you mind giving the latest version a try?

**Comment by GegznaV** [comment]
The situation is better now:
![image](https://user-images.githubusercontent.com/12725868/62775143-8383b200-baaf-11e9-843e-725d06e45477.png)

**Comment by nevrome** [comment]
And does the spellcheck with hunspell work as expected?

**Comment by GegznaV** [comment]
After updating to LangToolR v0.1.2 and accepting #8 the last (grammar check) add-in also works:

![image](https://user-images.githubusercontent.com/12725868/62842519-6fac9b80-bcbb-11e9-9cda-7daea2ea0716.png)

**Comment by nevrome** [comment]
I guess that's solved now?

**Comment by GegznaV** [comment]
It seems that RStudio 1.3 will have on-the-fly spelling checking possibilities:
https://stackoverflow.com/a/56320040/4783029

**Comment by GegznaV** [comment]
Solved.

**Comment by nevrome** [comment]
That's the main reason why I did not work on this package any more.

**Comment by nevrome** [comment]
But spellcheck is not grammar check. LanguageTool is useful far beyond spelling.
