### ISSUE TITLE
Why core dependencies are in "Suggests" and not in "Imports"?

### ISSUE THREAD

**Issue by GegznaV** [nevrome/wellspell.addin#9]
In `DESCRIPTION` file, packages **hunspell** and **LanguageToolR** arein section `"Suggests"`:

```yaml
Suggests:
  hunspell,
  LanguageToolR (>= 0.1.2)
```

These packages give core functionality for the add-in and dependencies in `"Suggests"` are not always downloaded. Shouldn't these packages be moved to `"Imports"` (or even `"Depends"`)?

**Comment by nevrome** [comment]
That's on purpose to make it possible to use the package without either hunspell or LanguageTool.

This code informs the user in case of a missing package:

https://github.com/nevrome/wellspell.addin/blob/501b472ac55a8aede5c2db97389edaca85f1ca5f/R/wellspell.R#L14

https://github.com/nevrome/wellspell.addin/blob/501b472ac55a8aede5c2db97389edaca85f1ca5f/R/wellspell.R#L61
